function espaniol(){
    $("#pGallery").text("Galería")
    $("#btnCerrarModalGallery").text("Cerrar")
    $("#pReservacion").text("Reservación")
    $("#pBienvenido").text("¡BIENVENIDO!")
    $("#pIndicacion_reservacion").text("Dar clic al botón, 'Enviar reservacion por mail'")
    $("#pIndicacion1_mail").text("¡Email enviado correctamente!")
    $("#pIndicacion2_mail").text("Muchas gracias por la reservación, en un momento uno de nuestros colaboradores se pondrá en contanto contigo.")
    $("#pFechaInicio").text("Llegada")
    $("#pFechaFin").text("Salida")
    $("#pNochesCosto").text("Noches")
    $("#pNochesRenta").text("Renta por noche")
    $("#pIndicacion1_nuevoUsuario").text("Muchas gracias por contactarnos, estamos contentos de poder ayudarte a reservar la residencia de tu elección")
    $("#pIndicacion2_nuevoUsuario").text("Por favor, captura la informacion que necesitamos para activar tu cuenta")
    $("#pNombreUsuario").text("Nombre")
    $("#txtNombre").attr("placeholder","Nombre")
    $("#pCelular").text("Celular (WhatsApp)")
    $("#pCelular").attr("placeholder","Celular (10 Digitos)")
    $("#pEmail").text("Email")
    $("#pEmail").attr("placeholder","Email")
    $("#spanEmail").text("¡ERROR!, Este email esta actualmente registrado, agrega otro email ó da clic a la opción 'YA SOY CLIENTE' y despues da clic en 'ENVIAR CODIGO DE ACCESO' ")
    $("#btnRegistrarCliente").text("Enviar clave de activación por email")
    $("#btnYaSoyCliente").text("¡Ya soy cliente!")
    $("#pIndicacionActivacion").text("Captura la clave enviada a tu email")
    $("#txtClave").attr("placeholder","Clave")
    $("#spanClave").text("¡Debes capturrar la clave enviado a tu email!")
    $("#btnActivarCuenta").text("Activar cuenta")
    $("#btnReenviarCorreo").text("No he recibido la clave, reenviar email")
    $("#pIndicacionesInicioSesion").text("Por favor captura tu email y clave de activación")
    $("#pEmailSesion").text("Email")
    $("#txtEmailLogeo").attr("placeholder","Email")
    $("#pClaveSesion").text("Clave")
    $("#txtClaveLogeo").attr("placeholder","Clave")
    $("#btnIniciarSesion").text("INICIAR SESIÓN")
    $("#btnNoRecuerdoclave").text("¿ No recuerdas la clave ?, Enviar clave de acceso por email")
    $("#btnCerrarModalFechas").text("CERRAR")
    $("#pMenuHome").text("INICIO")
    $("#pMenuRegresar").text("Regresar")
    $("#pTituloModelos").text("MODELOS")
    $("#pIndicacion1Modelos").text("A continuación se muestran los modelos de casas que conforman el fraccionamiento MaryGold, las fotos son solo referencia de las casas que existen en el modelo seleccionado")
    $("#pIndicacion2Modelos").text("Para ver y rentar una casa, haga clic en 'Ver Casas'")
    $("#backModelos").text("MODELOS")
    $("#pHouses").text("RESIDENCIAS")
    $("#pInidicacion1Casas").text("El listado de casas que se muestran a continuación son para rentar, las fotos son solo referencia de las casas que existen en el modelo seleccionado")
    $("#pInidicacion2Casas").text("Para rentar una casa dar clic en 'Ver fechas'")
    // $("#").text("")
    // $("#").text("")
    // $("#").text("")

}

function ingles(){
    $("#pGallery").text("Gallery")
    $("#btnCerrarModalGallery").text("Close")
    $("#pReservacion").text("Reservation")
    $("#pBienvenido").text("WELCOME!")
    $("#pIndicacion_reservacion").text("Click the button 'Send reservation by mail'")
    $("#pIndicacion1_mail").text("Mail sent successfully!")
    $("#pIndicacion2_mail").text("Thank you very much for the reservation, in a moment one of our advisors will contact you!")
    $("#pFechaInicio").text("Arrival time")
    $("#pFechaFin").text("Departure time")
    $("#pNochesCosto").text("Nights")
    $("#pNochesRenta").text("Rent per night")
    $("#pIndicacion1_nuevoUsuario").text("Thank you very much for contacting us, we will be happy to help you reserve the residence of your choice")
    $("#pIndicacion2_nuevoUsuario").text("Please enter the information we request to activate your account")
    $("#pNombreUsuario").text("Name")
    $("#txtNombre").attr("placeholder","Name")
    $("#pCelular").text("Phone (WhatsApp)")
    $("#pCelular").attr("placeholder","Phone (10 Digit)")
    $("#pEmail").text("Mail")
    $("#pEmail").attr("placeholder","Mail")
    $("#spanEmail").text("ERROR! This email has already been registered before, add another email or click on the option I AM ALREADY A CUSTOMER and then click on SEND ACCESS CODE")
    $("#btnRegistrarCliente").text("Send activation key by mail")
    $("#btnYaSoyCliente").text("I'm already a customer!")
    $("#pIndicacionActivacion").text("Enter the key sent to your mail")
    $("#txtClave").attr("placeholder","Key")
    $("#spanClave").text("You must capture the key sent to your mail!")
    $("#btnActivarCuenta").text("Activate account")
    $("#btnReenviarCorreo").text("I did not receive the key, resend mail")
    $("#pIndicacionesInicioSesion").text("Please enter your mail and activation key")
    $("#pEmailSesion").text("Mail")
    $("#txtEmailLogeo").attr("placeholder","Mail")
    $("#pClaveSesion").text("Key")
    $("#txtClaveLogeo").attr("placeholder","Key")
    $("#btnIniciarSesion").text("LOG IN")
    $("#btnNoRecuerdoclave").text("Don't remember the password?, Send access key by mail")
    $("#btnCerrarModalFechas").text("CLOSE")
    $("#pMenuHome").text(" HOME")
    $("#pMenuRegresar").text("Go back")
    $("#pTituloModelos").text("MODEL")
    $("#pIndicacion1Modelos").text("Below are the models of houses that make up the subdivision MaryGold, the photos are only a reference of the houses that exist in the selected model")
    $("#pIndicacion2Modelos").text("To view and rent a home, click 'View Houses'")
    $("#backModelos").text("MODELS")
    $("#pHouses").text("HOUSES")
    $("#pInidicacion1Casas").text("The list of houses that are shown below are for rent, the photos are only a reference of the houses that exist in the selected model")
    $("#pInidicacion2Casas").text("To rent a house click on 'View dates'")
    // $("#").text("")
    // $("#").text("")
    // $("#").text("")
}


var idioma = 2

$(".idioma").on("click", function(){
    idioma = $(this).attr("id")
    
    // console.log(window.idioma)

    if(idioma == 1){
        espaniol()
    }else if(idioma == 2){
        ingles()
    }
})